# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/fubalapp-graphql
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "85:85:c9:3a:62:b9:f0:7d:f1:85:d6:dd:1f:d6:48:f2"
            - "b3:6e:85:62:35:17:00:98:92:ab:18:ef:24:3f:3d:d3"
      - run:
          name: Get dependencies
          command: go get ./...
      - run:
          name: Build
          command: go build -o server
      - run:
          name: Add host to known hosts
          command: ssh-keyscan $SSH_HOST >> $HOME/.ssh/known_hosts

      - run:
          name: Stop service
          command: |
            ssh $SSH_USER@$SSH_HOST "sudo systemctl stop fubalapp.service"
      - run:
          name: Move binary file
          command: |
            scp server $SSH_USER@$SSH_HOST:/home/ubuntu/fubalapp
      - run:
          name: Restaer service
          command: |
            ssh $SSH_USER@$SSH_HOST "sudo systemctl restart fubalapp.service"




#version: 2
#
#jobs:
#  build:
#    machine:
#      enabled: true
#    steps:
#      - add_ssh_keys:
#          fingerprints:
#            - "62:57:9d:cc:d0:08:68:f0:a0:d1:15:3f:1f:71:98:09"
#      - run:
#          name: Build
#          command: |
#            ssh $SSH_USER@$SSH_HOST "/home/ubuntu/build"
#  deploy:
#    machine:
#      enabled: true
#    steps:
#      - run:
#          name: Deploy Over SSH
#          working_directory: /usr/local/go/src/
#          command: |
#            ssh $SSH_USER@$SSH_HOST "/usr/local/go/src/fubalapp-graphql/server"
#
#workflows:
#  version: 2
#  build-and-deploy:
#    jobs:
#      - build
#      - deploy:
#          requires:
#            - build # only deploy once build job has completed
#          filters:
#            branches:
#              only: master # only deploy on the master branch