version: 2

jobs:
  build:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "62:57:9d:cc:d0:08:68:f0:a0:d1:15:3f:1f:71:98:09"
      - run:
          name: provaaaa
          working_directory: /usr/local/go/src/
          command: |
            ssh $SSH_USER@$SSH_HOST "echo ciaoooo $USER"
      - run:
          name: Build
          command: |
            ssh $SSH_USER@$SSH_HOST "go build -o server"
  deploy:
    machine:
      enabled: true
    steps:
      - run:
          name: Deploy Over SSH
          command: |
            ssh $SSH_USER@$SSH_HOST "<remote deploy command>"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build # only deploy once build job has completed
          filters:
            branches:
              only: master # only deploy on the master branch