version: 2

jobs:
  build:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "c1:a1:2d:2e:ca:b2:3b:9b:25:83:8d:52:37:f9:55:d3"
            - "b9:70:04:09:2b:99:6c:80:a1:94:e8:36:6b:ca:d6:da"
      - run:
          name: provaaaa
          working_directory: /usr/local/go/src/
          command: |
            ssh $SSH_USER@$SSH_HOST "echo ciaoooo $USER"
      - run:
          name: Build
          command: |
            ssh $SSH_USER@$SSH_HOST "go build -o server"
  deploy:
    machine:
      enabled: true
    steps:
      - run:
          name: Deploy Over SSH
          command: |
            ssh $SSH_USER@$SSH_HOST "<remote deploy command>"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build # only deploy once build job has completed
          filters:
            branches:
              only: master # only deploy on the master branch